### ISSUE TITLE
Readme contains "none" when I attempt to add a line break

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#177]
This is minor but when i attempt to update my repo / readme running `abc-new-template --mode merge` the readme has a `none` in it instead of a line break. Examples of the readme and the config are below! i just updated abc-classroom tonight so i'm working off of 0.0.14 on pypi! 

BUT the readme is rendering better now - no list of assignments in there!! It would be neat if we could grab the assignment name from the CLI call and insert it into the readme somehow automagically but this is really minor and just a future enhancement idea. for the time being fixing the none is definitely a good idea! 

<img width="688" alt="Screen Shot 2020-02-11 at 6 12 32 PM" src="https://user-images.githubusercontent.com/7649194/74294126-3ac8e200-4cfa-11ea-8e69-2c41a0261a76.png">
<img width="711" alt="Screen Shot 2020-02-11 at 6 13 14 PM" src="https://user-images.githubusercontent.com/7649194/74294125-38ff1e80-4cfa-11ea-8aa4-869f1d6d44d9.png">

**Comment by kcranston** [comment]
This is due to yaml syntax - that line is equivalent to a value of `None`. If you wanted whitespace, you could use `\n` or `"\ "`. Otherwise, we could parse the contents of the `README.md` key and replace `None` values with newlines when generating this file. 

An alternate approach would be to generate the `README.md` as a file during quickstart, and use that to create the README for each assignment. This would make editing the content easier, although then we would have to deal with how to do variable replacement. 

As for the assignment name - we are doing that. `#ea-python-2020-what-the-fork-who-did-this` is the header line in the README. Are you looking for something else?

**Comment by lwasser** [comment]
closing this as we've removed the auto readme item!!
