### ISSUE TITLE
Update documentation surrounding the create of the README FILE. 

### ISSUE THREAD

**Issue by kcranston** [earthlab/abc-classroom#178]
This issue is to collect suggestions for documentation improvements (to avoid many small PRs):

- [x] [configuration](https://abc-classroom.readthedocs.io/en/latest/configuration.html) - currently blank
- [ ] readme - add information about how README.md gets created during template creation, and how to modify the contents 
- [x] requirement for SSH keys and a link to the GitHub guide on setting these up
- [x] formatting on the [nbgrader section of the course materials page](https://abc-classroom.readthedocs.io/en/latest/course-materials.html#managing-course-materials-using-nbgrader)

**Comment by lwasser** [comment]
we did a pretty big overhaul of docs a few months ago. 

- [ ] [i did add the SSH stuff and have been updating it!! ](https://abc-classroom.readthedocs.io/en/latest/collect-grade-assignments/clone.html#setup-ssh-to-ensure-abc-clone-runs-properly) it does have to be smaller pr's because i think i have it all covered and then something else comes up like the jupyter hub stuff!!
- [ ]  [configuration is still empty.](https://abc-classroom.readthedocs.io/en/latest/get-started/configuration.html) i guess this is an overview of the config file. but there is some content here that could be moved -- https://abc-classroom.readthedocs.io/en/latest/manage-assignments/new_assignment.html#configuration-settings 
- [ ] readme info -- not sure that is documented at all
- [ ] we probably do want to update the [nbgrader page with more details a bout how to format a notebook?](https://abc-classroom.readthedocs.io/en/latest/manage-assignments/create-grade-assignment-workflow.html#notebook-design)

**Comment by lwasser** [comment]
Let's in this issue just focus on making sure we update the documentation to discussion how the README.md file is created when you create a template repo. 

The readme and gitignore comes from below 
and it uses the title of the assignment maybe?? -- NEED TO CHECK
https://github.com/earthlab/abc-classroom/tree/main/abcclassroom/example-data/extra_files

**Comment by lwasser** [comment]
we aren't supporting....

IF you want every readme to be updated, modify the `readme.md` file from the `extra_files` directory.  (it will only update new repos that we create)... the template repo for new assignments.

**Comment by lwasser** [comment]
I am going to add this documentation here:

https://abc-classroom.readthedocs.io/en/latest/manage-assignments/new_assignment.html#how-to-create-and-update-template-repositories 

@kcranston should i update this as well https://abc-classroom.readthedocs.io/en/latest/manage-assignments/new_assignment.html#text-editors-and-git-commit-messages as it talked about the text editor opening which is an issue we will close with  #471
