### ISSUE TITLE
support extra-files - a dir which contains files that we wish to move over to all templates

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#195]

**Comment by kcranston** [comment]
Would like some input on the workflow for setting up a new course. My current plan is to modify what's in [`example-data`](https://github.com/earthlab/abc-classroom/tree/master/abcclassroom/example-data) to remove the extra_files section of the template config and instead create an extra_files directory with the two default files. We then want to copy that extra_files directory into the course_materials directory. Structure we would like (or maybe you want `extra_files` inside `release`?):

```
- top-level course dir
  - assignment_repos
  - cloned_repos
  - course_materials
     - extra_files
     - release
```

The problem is that `abc-quickstart` doesn't create the course_materials folder, because 1) users might already have a directory of course materials; or 2) they might use nbgrader's quickstart to create the course_materials directory. So, I am not sure the best way to orchestrate this. Options:

* user runs `abc-quickstart`, then manually creates the `course_materials` directory, then runs another abc script to create the `extra_files` dir
* user runs `abc-quickstart`, which creates `course_materials` and `course_materials/extra-files`. Then, user manually renames / moves stuff if they want to use a different directory for course materials
* user runs `abc-quickstart`, which creates `extra_files` in the top-level course directory. We could then either have them move `extra_files` manually into `course_materials` or just have the template script look for extra-files in the top-level dir

**Comment by lwasser** [comment]
let's have quickstart put the extra_files dir in the root abc dir given our discussion on slack @kcranston ! that does seem like a nice simple way to set things up.
