### ISSUE TITLE
error when running abc-quickstart - can't find extra_files directory

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#272]
i ran into this error just now trying to install abc-quickstart. i do see that i have python 3.7 installed vs 3.8...

but we should start working on these bugs. 
```
(earth-analytics-python) CIRES-EL-LM-020:1-bootcamp-course leahwasser$ abc-quickstart fall-2020-abc-bootcamp
Traceback (most recent call last):
  File "/Users/leahwasser/miniconda3/envs/earth-analytics-python/bin/abc-quickstart", line 10, in <module>
    sys.exit(quickstart())
  File "/Users/leahwasser/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/__main__.py", line 32, in quickstart
    create_dir_struct(course_name, args.f)
  File "/Users/leahwasser/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/quickstart.py", line 100, in create_dir_struct
    extra_path = path_to_example("extra_files")
  File "/Users/leahwasser/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/quickstart.py", line 33, in path_to_example
    raise FileNotFoundError(dataset_path)
FileNotFoundError: /Users/leahwasser/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/example-data/extra_files
```

i got the same issue when working on the hub. so i suspect it's a true bug.
@nkorinek this would be a good thing for you to start working on.

**Comment by lwasser** [comment]
just a note that this error is actually impacting every single abc command line option... so we will need to fix this first. @nkorinek definitely let's start with this bug

**Comment by nkorinek** [comment]
@lwasser this is an interesting bug! This is broken when freshly installed with pip or conda when gotten like `pip install abc-classroom`. However, if installed from the latest version on github using `pip install -e .`, the error doesn't show. The change to how commands like `abc-quickstart` work was made in the the pr that was merged 12 days ago #261 . In the pr, it adds in an extra `extra_files` folder, and changes `abc` commands to use files from that folder. 

While that folder exists on github, when abc-classroom is installed via conda or pip, the folder is not present. I have no idea why. The changes were made in the same pr, so it can't be a versioning issue. If you add the `extra_files` folder to the install on your computer when installed with conda or pip, then everything runs as expected. I checked all the pr's since this change was made and in none of them was that folder removed. Somehow that folder didn't make it when abc-classroom's latest version was pushed up to pip and conda. 

The short term fix is to either just install it via github or add the `extra_files` folder by manually copying it into the conda install. The long term fix is to figure out why it hasn't made it up to the online versions of abc-classroom.

I hope this helps! Let me know if you have any other questions.

**Comment by lwasser** [comment]
@nkorinek abc-quickstart should create the extra_files directory just like it creates the other directories. 
So why is it failing when we try to run it. it should create that stuff. thoughts?

**Comment by lwasser** [comment]
Ok so as i understand it - when we run abc-quickstart at the command line it essentially COPIES the stuff in the example_data directory rather than creating it. What is happening is when i pushed out the distribution (version 0.1.0) that extra files dir did not get included. 

1. i am not sure why it didn't get included and 
2. i wonder if we want to just create that directory anyway ?

@kcranston @mbjoseph do either of you know how to ensure a directory of example files gets bundled with a pip or conda distribution? 

@kcranston do we need to copy the directory vs just creating a few files in it with a readme? what is the best approach?
Essentially all of our command line functions are broken now but they work when you install the dev version of this tool.

**Comment by lwasser** [comment]
note -- https://pypi.org/project/abc-classroom/#files i can see when i release a version that directory is NOT included int he bundle. so maybe just creating the directory is easiest but i'd also like to understand why it's not being bound into the zip  tar.gz package

**Comment by lwasser** [comment]
update - it occurred to me i have to explicetly bundle it. trying that here. this is hard because i can't test it locally as it installs correctly locally. 

https://github.com/earthlab/abc-classroom/commit/fe93829218de8dffcd0507fd3283d88adfab9fd1

**Comment by lwasser** [comment]
that didn't work :/ the only file that is copying over is the config.yml file. nothing else is copying

**Comment by nkorinek** [comment]
Oh no I was hoping that would work!

**Comment by lwasser** [comment]
me too..i wonder if it is because the package is called abc-classroom but the directory is abcclassroom (without the dash). but it's also weird that config.yml IS bundling and nothing else. i don't understand that either

**Comment by lwasser** [comment]
Ok i may have something. i updated the manifest file - here - https://github.com/earthlab/abc-classroom/commit/b9d7fd0ab22dd76218b1d532dd9dbf91c00ab714 
it worked locally but i can't figure out how to add the .gitignore to it. luckily the gitignore isn't all that important! we can make one. will test tomorrow!! weird that this worked differently in earthpy but here the manifest was needed for the data files.

**Comment by kcranston** [comment]
Based on [python packaging docs](https://packaging.python.org/guides/using-manifest-in/) like we should probably use `graft example-files` to include the whole example-files dir and its contents.

**Comment by lwasser** [comment]
ok great! i'll work on testing that later today and will build the wheel locally! now that i know that is easy to do i can test it out and push another release maybe when we have a few other kinks sorted out!! 
thank you

**Comment by lwasser** [comment]
this worked. i did graft abcclassroom/example-files !! thank you @kcranston i'll be pushing up a pr for this now!

**Comment by lwasser** [comment]
this change has been merged but i am going to bump another version to check to see that it works properly. this will take a day or so to fully implement BUT i'll do it now. it will bump to patch 0.1.5

**Comment by lwasser** [comment]
this bug is still happening - on the hub version 0.1.5 which is the most recent version that i pushed
```
jovyan@jupyter-earth-2dlab:~$ abc-quickstart delete
Sample config.yml configuration file cannot be located at /opt/conda/lib/python3.8/site-packages/abcclassroom/example-data/config.yml,
        please ensure abc-classroom has been installed
        correctly
Traceback (most recent call last):
  File "/opt/conda/bin/abc-quickstart", line 10, in <module>
    sys.exit(quickstart())
  File "/opt/conda/lib/python3.8/site-packages/abcclassroom/__main__.py", line 32, in quickstart
    create_dir_struct(course_name, args.f)
  File "/opt/conda/lib/python3.8/site-packages/abcclassroom/quickstart.py", line 86, in create_dir_struct
    copy(config_path, main_dir)
UnboundLocalError: local variable 'config_path' referenced before assignment
```

i haven't had time to trouble shoot this but it seems like it's still struggling to find all of the correct files in the package.

**Comment by nkorinek** [comment]
It is indeed still having a hard time finding the correct files, because they again don't seem to exist! When I install `abc-classroom` from conda or pip, I get the following file structure in the install directory. 
![image](https://user-images.githubusercontent.com/38253680/94083801-4e284980-fdc1-11ea-8aa2-25deaef1f5d1.png) 
As you can see, the `example_data` folder is missing entirely! Last time I believe we were only missing the subdirectory called `extra_files`, but the whole `example_data` folder is missing now. 

I think you got that whole error instead of just the top part because the code doesn't raise an actual error if it fails, just prints a statement, which is an easy fix. 

But that's not the main issue, the main issue now is figuring out why that `example_data` folder is missing from the install. @lwasser

**Comment by kcranston** [comment]
Looks like [this commit](https://github.com/earthlab/abc-classroom/commit/ae33fea28ac5f13e97c0767f1ce6f2ab0302a745) grafted a directory called `example-files` rather than `example-data` (and note that it is a hyphen, not an underscore).

**Comment by lwasser** [comment]
oooh you are so right @kcranston i'm losing my mind. i've been making a lot of really silly mistakes like this lately.  THANK YOU
i think when i tested it locally i just made sure the dir was packaged and my brain just thought it should be `example-files`

**Comment by lwasser** [comment]
this one as well @nkorinek just do a quick test and if it looks good we can close both issues!! i just want someone other than me to confirm :)

**Comment by nkorinek** [comment]
@lwasser this one works as well!

**Comment by lwasser** [comment]
yahoo!! closing!
