### ISSUE TITLE
jupyter_client.kernelspec.NoSuchKernel errror with circleci 

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#48]
Please see this repo for my submitted assignment! 
https://github.com/earth-analytics-edu/ea-spring-2019-lwasser/commits/master

This appears to be a kernel error. [see circleCI feedback here](https://circleci.com/gh/earth-analytics-edu/ea-spring-2019-lwasser/21)

```
jupyter_client.kernelspec.NoSuchKernel: No such kernel named conda-env-earth-analytics-python-py
Exited with code 1
```
But i also wonder why check() `isn't` working locally and if this is all related.

**Comment by betatim** [comment]
This is related to the discussion in #20.

On your laptop you have a specially named kernel that launches in a particular conda environment. However there is no kernel with that name on CircleCI because the environment there has a different name and the particular notebook extension that creates a kernel for each environment isn't installed.
